config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :stocks
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stocks_controller.rb
#to get params from form, use params[:field].inspect
#

class StocksController < ApplicationController
    def new
    end

    def create
      scraper = StocksHelper::StockScraper.new(stock_search_params[:stockTicker])

      render 'stocks/stockinfo', locals: {resource: scraper.scrape, name: stock_search_params[:stockTicker]}

    end

    def index

    end


  private
    def stock_search_params
      params.require(:stock).permit(:stockTicker)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
require 'nokogiri'
require 'open-uri'
require 'openssl'
#To prevent openssl errors
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE


module StocksHelper

  class StockScraper
    attr_reader :stockTicker

    #constructor, initializes stock name
    def initialize(stockName)
      puts "Stock name to search for is: " + stockName
      @stockTicker = stockName
    end

    #top caller of scraping all data
    #will return all scraped data and perform assesment
    def scrape()
      scrapeForCurrentData
    end

    private
      #to scrape for current intraday data
      def scrapeForCurrentData()
        url = "https://ca.finance.yahoo.com/quote/" + @stockTicker + "/key-statistics?"
        result = {}
        page = Nokogiri::HTML(open(url))
        main_contents = page.css('tr td')
        main_contents.search('sup').remove
        main_contents.each_with_index do |content, index|
          if index%2 == 0
            result[content.text] = main_contents[index+1].text
          end
        end
        #puts result
        return result
      end

    # scrape for annual income statement
    # reurns array of income statement objects
    def scrapeForIncomeStatement()
      result = [[]]
      url = "https://ca.finance.yahoo.com/quote/" + @stockTicker + "/financials?p="+ @stockTicker
      page = Nokogiri::HTML(open(url))
      table = page.at('table')
      rows = table.css('tr')
      rows.each do |row|
        row = row.css('td')
        temp_arr = []
        row.each do |data|
          temp_arr.push(data.text)
        end
        result.push(temp_arr)
      end
      result.delete_at(0)
      final_result = []
      number_of_columns = result[0].length
      for i in 0..number_of_columns-1 do
        column_data = {}
        result.each do |data|
          column_data[data[0]] = data[i]
        end
        final_result.push(column_data)
      end
      #puts final_result
      return final_result
    end


    def scrapeForBalanceSheet()
      result = [[]]
      url = "https://ca.finance.yahoo.com/quote/" + @stockTicker + "/balance-sheet?p="+@stockTicker
    end

    def scrapeForCashFlow()

    end




  end


end

app/views/home/index.html.erb
<head>
</head>


<body>
    <%= link_to 'Stock Analyzer', stocks_path %>

</body>

<footer>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockAnalyzer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/index.erb
<%= link_to 'create new', new_stock_path %>

app/views/stocks/new.html.erb
<%= form_with scope: :stock, url: stocks_path ,local: true do |form|%>
  <p>
      <%= form.label :stockTicker, 'Name of stock to search for' %>
      <%= form.text_field :stockTicker %>
  <p>

  <p>
    <%= form.submit "Search for stock" %>
  </p>
<% end %>

app/views/stocks/stockinfo.html.erb
<head>


  <title>Info</title>
  <h1> Stock Info of <%= name %></h1>


</head>


<body>
<!-- print out contents of stock data-->
<% resource.each do |title, value| %>
  <div class="stock_info">
    <%= title %>: <%= value %>
  </div>
<% end %>

</body>